# Generated by Django 3.2.7 on 2021-09-19 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carmodel',
            table='cars',
        ),
    ]
