# Generated by Django 3.2.7 on 2021-09-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('country_of_manufacture', models.CharField(max_length=255)),
                ('length', models.IntegerField()),
                ('height', models.IntegerField()),
                ('wingspan', models.IntegerField()),
                ('load_capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'planes',
            },
        ),
    ]
