# Generated by Django 3.2.7 on 2021-09-28 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planemodel',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planemodel',
            name='length',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100000, 'Too much')]),
        ),
        migrations.AlterField(
            model_name='planemodel',
            name='load_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planemodel',
            name='wingspan',
            field=models.IntegerField(default=0),
        ),
    ]
